# Generated by Django 2.0.13 on 2020-01-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_remove_phonesfileformat_field_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhonesFileFormat',
            new_name='PhonesFieldsFormat',
        ),
    ]
