# Generated by Django 2.0.13 on 2020-01-21 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200119_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
