# Generated by Django 2.0.13 on 2020-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
